apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
  namespace: kubernetes-demo-node-port
spec:
  selector:
    app: kubernetes-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort